name: oracle
version: 0.1.0
description: >
  Dart library for Oracle database access.

homepage: https://github.com/oracle-dart/oracle.dart
environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  ffi: ^2.1.0
  grinder: ^0.9.5
dev_dependencies:
  logging: ^1.2.0
  test: ^1.25.1
  # dart_coveralls: ^0.4.0
