name: oracle
version: 0.1.0
description: >
  Dart library for Oracle database access.
authors: 
- Michael Loveridge
- Chris Lucas 
- Austin Cummings
homepage: https://github.com/oracle-dart/oracle.dart
dependencies:
  grinder: ^0.7.2
dev_dependencies:
  logging: ^0.11.1
  test: ^0.12.4+3
  dart_coveralls: ^0.4.0
